### ISSUE TITLE
no fallback?

### ISSUE THREAD

**Issue by SwissalpS** [S-S-X/beerchat#1]
https://github.com/S-S-X/beerchat/blob/83ffafa7d380b656d19ce5674c60f36ba1f54ec4/jail.lua#L7

am I missing some place you fall back to a default values if these are not set in server config?

**Comment by S-S-X** [comment]
yes you are missing something, first local tells you that it should not be used very far away from there.

whole block here: https://github.com/S-S-X/beerchat/blob/master/jail.lua#L7-L13

**Comment by SwissalpS** [comment]
ouch, should not read code when coming straight from bed. Sorry my bad I skipped 'owner or'.
Thanks for your patience with me :)
